/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import model.Usuario;
import util.Alert;

/**
 *
 * @author IzaltinoNeto
 */
public class CabecalhoUsuarioComponente extends javax.swing.JPanel {

    /**
     * Creates new form CabecalhoUsuarioComponente
     */
    //@SuppressWarnings("OverridableMethodCallInConstructor")
    public CabecalhoUsuarioComponente() {
        initComponents();
        
    
//        comboTipoUsuario.addItem(TOOL_TIP_TEXT_KEY);
    }
    
    public JLabel getNome(){
        return this.nome;
    }
    
    public JComboBox getComboTipo(){
    return comboTipoUsuario;
    }
    
    public JButton getBotaoOpcoes(){
        return botaoOpcoes;
    }
    
    public JMenuItem getItemAlterarSenha(){
        return itemAlterarSenha;
    }
    public JMenuItem getItemLogout(){
        return itemLogout;
    }
    
    

    private void realizarAcao(MouseEvent evt){
                if(evt.getButton()==MouseEvent.BUTTON1){
            testePopup.show(evt.getComponent(), -70,30);
            System.out.println("X= "+evt.getX()+ " y= "+evt.getY());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        testePopup = new javax.swing.JPopupMenu();
        itemAlterarSenha = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        nome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        botaoOpcoes = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        testePopup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        testePopup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        itemAlterarSenha.setText("AlterarSenha");
        testePopup.add(itemAlterarSenha);

        itemLogout.setText("Logout");
        testePopup.add(itemLogout);

        nome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nome.setText("Testing");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Monitor", "Coordenador" }));
        comboTipoUsuario.setMinimumSize(new java.awt.Dimension(40, 15));
        comboTipoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoUsuarioItemStateChanged(evt);
            }
        });

        botaoOpcoes.setText("...");
        botaoOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoOpcoesMouseClicked(evt);
            }
        });
        botaoOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboTipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOpcoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOpcoesActionPerformed
     
    }//GEN-LAST:event_botaoOpcoesActionPerformed

    private void botaoOpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoOpcoesMouseClicked
        realizarAcao(evt);
    }//GEN-LAST:event_botaoOpcoesMouseClicked

    private void comboTipoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoUsuarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoUsuarioItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOpcoes;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JMenuItem itemAlterarSenha;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nome;
    private javax.swing.JPopupMenu testePopup;
    // End of variables declaration//GEN-END:variables
}
