/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import model.Usuario;
import util.Alert;

/**
 *
 * @author IzaltinoNeto
 */
public class CabecalhoUsuarioComponente extends javax.swing.JPanel {

    /**
     * Creates new form CabecalhoUsuarioComponente
     */
    //@SuppressWarnings("OverridableMethodCallInConstructor")
    public CabecalhoUsuarioComponente() {
        initComponents();
        
      carregarMenu();
        
    }
    
    public JLabel getNome(){
        return this.nome;
    }
    
    public JComboBox getComboTipo(){
    return comboTipoUsuario;
    }
    
    public JButton getBotaoOpcoes(){
        return botaoOpcoes;
    }
    
    private void carregarMenu(){
    //criando item do menu
    JMenuItem itemAlterarSenha=new JMenuItem("Alterar Senha");
    JMenuItem itemLogout=new JMenuItem("Logout");
    //ação do item de menu
    /*itemAlterarSenha.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           
                try {
                 if(Alert.alertaExclusao(controle.getCategoria())==0){
                    controle.deletar();
                 }
                } catch (SQLException ex) {
                    Logger.getLogger(CategoriaPesquisarTela.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DAOException ex) {
                    Logger.getLogger(CategoriaPesquisarTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
    });*/
    //adicionando o item ao menu PopUp
    testePopup.add(itemAlterarSenha);
    testePopup.add(itemLogout);
    }

    private void realizarAcao(MouseEvent evt){
                if(evt.getButton()==MouseEvent.BUTTON1){
            testePopup.show(evt.getComponent(), -70,30);
            System.out.println("X= "+evt.getX()+ " y= "+evt.getY());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        testePopup = new javax.swing.JPopupMenu();
        nome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        botaoOpcoes = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        testePopup.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(204, 204, 204), null, null));
        testePopup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nome.setText("IzaltinoNeto");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Monitor", "Coordenador" }));

        botaoOpcoes.setText("...");
        botaoOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoOpcoesMouseClicked(evt);
            }
        });
        botaoOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOpcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(comboTipoUsuario)
                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOpcoesActionPerformed
     
    }//GEN-LAST:event_botaoOpcoesActionPerformed

    private void botaoOpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoOpcoesMouseClicked
        realizarAcao(evt);
    }//GEN-LAST:event_botaoOpcoesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOpcoes;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nome;
    private javax.swing.JPopupMenu testePopup;
    // End of variables declaration//GEN-END:variables
}
