/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import mvc.LoginMVC2;

/**
 *
 * @author sandr
 */
public class CoordenadorPesquisarMonitoriaTela extends javax.swing.JFrame {

    /**
     * Creates new form MonitoriaPesquisaTela
     */
    public CoordenadorPesquisarMonitoriaTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        cpPesquisa = new javax.swing.JTextField();
        btCadastar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btDetalhar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cabecalhoUsuarioComponente1 = new view.CabecalhoUsuarioComponente();
        jSeparator1 = new javax.swing.JSeparator();
        btGerenciarMaterias = new javax.swing.JButton();
        btGerenciarMonitores = new javax.swing.JButton();
        btGerenciarSalas = new javax.swing.JButton();
        btRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Monitoria");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        btCadastar.setText("Cadastrar");

        jLabel1.setText("Sala:");

        btPesquisar.setText("Pesquisar");

        btExcluir.setText("Excluir");

        btDetalhar.setText("Detalhar");

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btGerenciarMaterias.setText("<html>Gerenciar <br/>Matérias</html>");
        btGerenciarMaterias.setActionCommand("Gerenciar  Monitores");
        btGerenciarMaterias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btGerenciarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarMateriasActionPerformed(evt);
            }
        });

        btGerenciarMonitores.setText("<html>Gerenciar <br/>Monitores</html>");
        btGerenciarMonitores.setActionCommand("Gerenciar  Monitores");
        btGerenciarMonitores.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btGerenciarMonitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarMonitoresActionPerformed(evt);
            }
        });

        btGerenciarSalas.setText("<html>Gerenciar <br/>Salas</html>");
        btGerenciarSalas.setActionCommand("Gerenciar  Monitores");
        btGerenciarSalas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btGerenciarSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarSalasActionPerformed(evt);
            }
        });

        btRelatorios.setText("<html>Relatórios</html>");
        btRelatorios.setActionCommand("Gerenciar  Monitores");
        btRelatorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGerenciarMonitores, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btGerenciarMaterias)
                    .addComponent(btGerenciarSalas)
                    .addComponent(btRelatorios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cabecalhoUsuarioComponente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btPesquisar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btCadastar)
                                    .addGap(52, 52, 52)
                                    .addComponent(btDetalhar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btExcluir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cabecalhoUsuarioComponente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btCadastar)
                            .addComponent(btExcluir)
                            .addComponent(btDetalhar)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btGerenciarMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btGerenciarMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btGerenciarSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        LoginMVC2.main(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btGerenciarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarMateriasActionPerformed

    private void btGerenciarMonitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarMonitoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarMonitoresActionPerformed

    private void btGerenciarSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarSalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGerenciarSalasActionPerformed

    private void btRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btRelatoriosActionPerformed

    public JButton getBtCadastar() {
        return btCadastar;
    }

    public JTextField getCpPesquisa() {
        return cpPesquisa;
    }

    public JTable getTabela() {
        return tabela;
    }

    public JButton getBtPesquisar() {
        return btPesquisar;
    }

    public JButton getBtExcluir() {
        return btExcluir;
    }

    public JButton getBtDetalhar() {
        return btDetalhar;
    }
    
    public CabecalhoUsuarioComponente getUsuarioComponente(){
        return cabecalhoUsuarioComponente1;
    }
    
    public JButton getBtGerenciarMonitor(){
        return btGerenciarMonitores;
    }
    public JButton getBtGerenciarMaterias(){
        return btGerenciarMaterias;
    }
    public JButton getBtGerenciarSalas(){
        return btGerenciarSalas;
    }
    public JButton getBtRelatórios(){
        return btRelatorios;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoordenadorPesquisarMonitoriaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoordenadorPesquisarMonitoriaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoordenadorPesquisarMonitoriaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoordenadorPesquisarMonitoriaTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoordenadorPesquisarMonitoriaTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastar;
    private javax.swing.JButton btDetalhar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGerenciarMaterias;
    private javax.swing.JButton btGerenciarMonitores;
    private javax.swing.JButton btGerenciarSalas;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRelatorios;
    private view.CabecalhoUsuarioComponente cabecalhoUsuarioComponente1;
    private javax.swing.JTextField cpPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
